project_name = "clod"

[tasks]
build = {
  command = "strudel build",
  env = { APPLE_SIGNING_IDENTITY = "axo://apple/developer/dev-cert" }
}
bundle = {
  command = "strudel bundle",
  env = { APPLE_SIGNING_IDENTITY = "axo://apple/developer/dev-cert" }
}
install = ":build --install"
rust = "cargo install --path ."
